export const APP_ROLES = {
  admin: 'admin',
  editor: 'editor',
  agent: 'agent',
  teacher: 'teacher',
  student: 'student',
  superadmin: 'superadmin',
  institution: 'institution'
}

export const PERMISSIONS_VIA_ROLE = {
  [APP_ROLES.admin]: [
    '/dashboard',
    '/dashboard/insights',
    '/dashboard/academia',
    '/dashboard/addCollege',
    '/dashboard/category',
    '/dashboard/events',
    '/dashboard/faculty',
    '/dashboard/media',
    '/dashboard/news',
    '/dashboard/profile',
    '/dashboard/program',
    '/dashboard/scholarship',
    '/dashboard/university',
    '/dashboard/users',
    '/dashboard/agent',
    '/dashboard/agentApprove',
    '/dashboard/exams',
    '/dashboard/courses',
    '/dashboard/banner',
    '/dashboard/referrals',
    '/dashboard/material',
    '/dashboard/consultancy',
    '/dashboard/career',
    '/dashboard/vacancy'
  ],
  [APP_ROLES.editor]: [
    '/dashboard',
    '/dashboard/insights',
    '/dashboard/academia',
    '/dashboard/addCollege',
    '/dashboard/courses',
    '/dashboard/exams',
    '/dashboard/banner',
    '/dashboard/category',
    '/dashboard/events',
    '/dashboard/faculty',
    '/dashboard/media',
    '/dashboard/news',
    '/dashboard/profile',
    '/dashboard/program',
    '/dashboard/scholarship',
    '/dashboard/university',
    '/dashboard/users',
    '/dashboard/agent',
    '/dashboard/career',
    '/dashboard/consultancy',
    '/dashboard/level',
    '/dashboard/tag',
    '/dashboard/material'
  ],
  [APP_ROLES.agent]: ['/dashboard/referStudent', '/dashboard/profile'],
  [APP_ROLES.teacher]: [
    '/dashboard',
    '/dashboard/material',
    '/dashboard/profile'
  ],
  [APP_ROLES.student]: ['/dashboard', '/dashboard/profile'],
  [APP_ROLES.institution]: [
    '/dashboard',
    '/dashboard/profile',
    '/dashboard/applications',
    '/dashboard/edit-college'
  ],
  [APP_ROLES.superadmin]: ['*'] // Full access,
}
