export class EnvConfig {
  static NEXT_APP_API_BASE_URL = process.env.NEXT_APP_API_BASE_URL
  static NEXT_APP_API_VERSION_URL_PREFIX =
    process.env.NEXT_APP_API_VERSION_URL_PREFIX
  static NEXT_APP_MEDIA_BASE_URL = process.env.NEXT_PUBLIC_MEDIA_BASE_URL
  static NEXT_APP_CK_EDITOR_KEY = process.env.NEXT_APP_CK_EDITOR_KEY
}
